### ISSUE TITLE
Icons not saving

### ISSUE THREAD

**Issue by keithmancuso** [fyrebase/svg-icons#1]
Love the plugin but im having a pretty big issue, when i save the icon in the CMS it seems to save ok and theres content in the database like this

`{"icon":"category-icons\/Career Related.svg"}`

but when i reopen it the field is blank again?

any ideas

**Comment by fyrebase** [comment]
Thanks for reporting this issue @keithmancuso. I've released an updated version of the plugin with the fix.

Try it out and let me know if you have any more problems.
