### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by doespresso** [fyrebase/svg-icons#6]
Is it real to use with craft 3?

**Comment by fyrebase** [comment]
I haven't looked at converting this to Craft 3 yet. I'm waiting for Craft 3 to get out of beta and the API's to be locked down, but it is something I'm considering doing.

**Comment by terryupton** [comment]
Is this still on the agenda to convert to Craft 3? I am about to use this but want to check future compatibility.
Thanks.
